
title: "Harold Farf치n Reto"
author: "Harold Farf치n Reto"
description: "P치gina personal de Harold Farf치n Reto"
permalink: /:title/
lang: "es"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout
show_social: true         # show footer
show_excerpts: true       # show article excerpts on the home page
show_frame: false           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.md"}
  - {url: "/Harold_Farfan_Reto.pdf", title: CV}
  - {url: "http://childlanglab.com", title: Lab}
  - {file: "blog.md"}


external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:hfarfanreto@pm.me"}
  - {title: Github, icon: github, url: "https://github.com/hfarfanreto"}
  - {title: Twitter, icon: twitter, url: "https://twitter.com/KathrynSchuler"}


remote_theme: niklasbuschmann/contrast@v2.11

plugins:
  - jekyll-remote-theme
  - jekyll-feed

